export type EngineCapability = {
  repo: string;
  productName: string;
  lane: string;
  bestUse: string;
  featureUnlocked: string;
  integrationMode: "Native UI" | "Python worker" | "External engine" | "Research sandbox";
  safety: "Research" | "Paper trading" | "Live capable, gated";
  priority: "Now" | "Next" | "Later";
};

export const engineCapabilities: EngineCapability[] = [
  {
    repo: "OpenBB-finance/OpenBB",
    productName: "OpenBB Data Terminal",
    lane: "Market data",
    bestUse: "Market data, fundamentals, options chains, macro context, and CLI/Python research.",
    featureUnlocked: "Multi-source data terminal, research snapshots, macro/fundamental enrichment, options hooks.",
    integrationMode: "Python worker",
    safety: "Research",
    priority: "Next",
  },
  {
    repo: "RomelTorres/alpha_vantage",
    productName: "Alpha Vantage Data Worker",
    lane: "Free-account market data",
    bestUse: "Self-hosted Python access to Alpha Vantage time series, technical indicators, fundamentals, FX, crypto, and economic data with API-rate labels.",
    featureUnlocked: "Free-account provider lane that adds historical series and indicator context while making rate limits, provider warnings, and non-execution-grade freshness visible.",
    integrationMode: "Python worker",
    safety: "Research",
    priority: "Next",
  },
  {
    repo: "quantopian/alphalens",
    productName: "Alphalens Factor Tear Sheet",
    lane: "Factor performance analysis",
    bestUse: "Evaluate predictive alpha factors with forward returns, information coefficient, turnover, grouped analysis, quantile spreads, and tear sheets.",
    featureUnlocked: "Factor-proof lane that asks whether a signal actually ranks future returns before it can raise conviction.",
    integrationMode: "Python worker",
    safety: "Research",
    priority: "Next",
  },
  {
    repo: "wangzhe3224/awesome-systematic-trading",
    productName: "Systematic Trading Reference Map",
    lane: "Research ecosystem map",
    bestUse: "Classify the stack into data, alpha strategy, analytics, backtesting, live trading, architecture, tools, resources, and AI/LLM research lanes before accepting a decision.",
    featureUnlocked: "Native coverage checklist that turns curated systematic-trading resources into proof requirements, not copied source or an execution engine.",
    integrationMode: "Native UI",
    safety: "Research",
    priority: "Now",
  },
  {
    repo: "TauricResearch/TradingAgents",
    productName: "TradingAgents Debate Desk",
    lane: "Multi-agent research",
    bestUse: "LLM analyst, bull/bear researcher, trader, risk, and portfolio-manager debate before any paper-trade promotion.",
    featureUnlocked: "Structured research-only decisions, thesis/risk notes, and portfolio-manager challenges persisted to the research journal.",
    integrationMode: "Native UI",
    safety: "Research",
    priority: "Now",
  },
  {
    repo: "borisbanushev/stockpredictionai",
    productName: "StockPredictionAI Forecast Lab",
    lane: "Deep forecast research",
    bestUse: "Research-only stock-movement forecasts using GAN/LSTM/CNN concepts plus sentiment, Fourier, ARIMA, XGBoost, autoencoder, and PCA feature pressure.",
    featureUnlocked: "Heavy ML forecast lane with explicit overfit warnings and no direct route to broker execution.",
    integrationMode: "Python worker",
    safety: "Research",
    priority: "Next",
  },
  {
    repo: "Open-Dev-Society/OpenStock",
    productName: "OpenStock Companion",
    lane: "Open market app",
    bestUse: "Self-hosted stock search, watchlists, company insights, Finnhub/TradingView-style market views, alerts, and product-pattern comparison.",
    featureUnlocked: "Companion dashboard and alert UX pressure without importing AGPL source into the main app.",
    integrationMode: "External engine",
    safety: "Research",
    priority: "Next",
  },
  {
    repo: "shirosaidev/stocksight",
    productName: "StockSight Sentiment Worker",
    lane: "Social/news sentiment",
    bestUse: "Self-hosted Twitter and news headline sentiment mining with Elasticsearch storage, Kibana review, TextBlob/VADER/NLTK polarity, subjectivity, and link-following context.",
    featureUnlocked: "Source-labeled sentiment pressure that can challenge catalyst confidence while staying behind freshness, sample-size, and no-execution guardrails.",
    integrationMode: "Python worker",
    safety: "Research",
    priority: "Next",
  },
  {
    repo: "jef/streetmerchant",
    productName: "StreetMerchant Alert Ops",
    lane: "24/7 alert monitoring",
    bestUse: "Watch-loop discipline, dashboard status matrices, notification channel fanout, retry/cooldown policy, and manual-action confirmation patterns.",
    featureUnlocked: "Alert-operations pressure that keeps trigger state, channel readiness, cooldowns, and no-auto-buy guardrails visible next to trade ideas.",
    integrationMode: "External engine",
    safety: "Research",
    priority: "Next",
  },
  {
    repo: "ghostfolio/ghostfolio",
    productName: "Ghostfolio Portfolio Companion",
    lane: "Portfolio analytics",
    bestUse: "Self-hosted portfolio performance, holdings composition, transactions, imports/exports, allocation, and static risk analysis.",
    featureUnlocked: "Portfolio source-of-truth pressure that turns trade ideas into account-level exposure and concentration questions.",
    integrationMode: "External engine",
    safety: "Research",
    priority: "Next",
  },
  {
    repo: "akfamily/akshare",
    productName: "AKShare Data Worker",
    lane: "Free financial data",
    bestUse: "Python research access to China/Asia markets, macro series, futures, bonds, options, funds, and reference datasets.",
    featureUnlocked: "Broader free/self-hosted non-US data coverage with explicit academic/research-only data-risk labeling.",
    integrationMode: "Python worker",
    safety: "Research",
    priority: "Next",
  },
  {
    repo: "LuckyOne7777/LLM-Trading-Lab",
    productName: "LLM Trading Lab",
    lane: "LLM portfolio experiments",
    bestUse: "Forward-only LLM trading decision logs, daily portfolio experiments, hard constraints, stop-loss compliance, benchmark comparisons, and risk metrics.",
    featureUnlocked: "Research lane that pressure-tests LLM decisions against written constraints and portfolio outcomes without touching broker execution.",
    integrationMode: "Python worker",
    safety: "Research",
    priority: "Next",
  },
  {
    repo: "huseinzol05/Stock-Prediction-Models",
    productName: "Stock Prediction Models Lab",
    lane: "ML model zoo",
    bestUse: "Research-only comparisons across deep learning forecasts, stacking, simulations, TensorFlow.js demos, and reinforcement-learning agent experiments.",
    featureUnlocked: "Archived Apache-2.0 ML model zoo lane with explicit holdout, overfit, and paper-only constraints.",
    integrationMode: "Python worker",
    safety: "Research",
    priority: "Next",
  },
  {
    repo: "jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction",
    productName: "LSTM Time Series Forecast Baseline",
    lane: "Sequence forecast research",
    bestUse: "Keras LSTM sequence prediction baselines, stock-market sample windows, walk-forward forecast checks, and dependency-modernization pressure.",
    featureUnlocked: "A narrow LSTM baseline lane that challenges trend forecasts against holdout windows, stale dependency warnings, and simple benchmark comparisons.",
    integrationMode: "Python worker",
    safety: "Research",
    priority: "Next",
  },
  {
    repo: "QuantConnect/Lean",
    productName: "LEAN Engine Bridge",
    lane: "Institutional backtesting",
    bestUse: "Self-hosted event-driven algorithm research, multi-asset backtests, optimization runs, paper-trading evidence, brokerage-adapter review, and reproducible strategy reports.",
    featureUnlocked: "Professional backtest/optimization/paper/live architecture with strict promotion gates and no live orders through the worker bridge.",
    integrationMode: "External engine",
    safety: "Live capable, gated",
    priority: "Next",
  },
  {
    repo: "StockSharp/StockSharp",
    productName: "StockSharp C# Connector Lab",
    lane: "Multi-broker quant worker",
    bestUse: "C# strategy research, market-data ingestion, exchange/broker connector tests, and StockSharp adapter simulations outside Vercel.",
    featureUnlocked: "Apache-2.0 C#/.NET worker lane for StockSharp connectors while live orders stay behind platform acknowledgement and audit gates.",
    integrationMode: "External engine",
    safety: "Live capable, gated",
    priority: "Next",
  },
  {
    repo: "ricequant/rqalpha",
    productName: "RQAlpha Event Backtest Worker",
    lane: "Python event-driven backtesting",
    bestUse: "Event-driven stock, futures, and multi-security strategy simulations with Mod-based risk checks, scheduled logic, analyser output, and transaction-cost modeling.",
    featureUnlocked: "RQAlpha-style proof lane that asks whether simulated orders, fills, costs, holdings, and portfolio reports survive realistic event-loop constraints.",
    integrationMode: "Python worker",
    safety: "Research",
    priority: "Next",
  },
  {
    repo: "kernc/backtesting.py",
    productName: "Simple Backtest Lab",
    lane: "Fast validation",
    bestUse: "Lightweight stock and ETF strategy testing before using heavier engines.",
    featureUnlocked: "Phone-friendly first-pass backtests: moving-average, breakout, mean-reversion, drawdown checks.",
    integrationMode: "Native UI",
    safety: "Research",
    priority: "Now",
  },
  {
    repo: "polakowo/vectorbt",
    productName: "Vector Sweep Lab",
    lane: "Parameter research",
    bestUse: "Fast vectorized testing across many symbols and parameter combinations.",
    featureUnlocked: "Grid-search heatmaps, parameter sweeps, robustness checks, and overfit warnings.",
    integrationMode: "Python worker",
    safety: "Research",
    priority: "Next",
  },
  {
    repo: "mementum/backtrader",
    productName: "Backtrader Classic",
    lane: "Simulation",
    bestUse: "Mature strategy simulations, order models, broker abstractions, and learning workflows.",
    featureUnlocked: "Classic event-driven simulation lane for comparing results against LEAN and simple tests.",
    integrationMode: "Python worker",
    safety: "Paper trading",
    priority: "Later",
  },
  {
    repo: "nautechsystems/nautilus_trader",
    productName: "Nautilus Production Rail",
    lane: "Advanced execution infra",
    bestUse: "Production-grade event-driven trading infrastructure for serious live systems.",
    featureUnlocked: "Future hardened execution architecture, adapter model, and operational readiness checklist.",
    integrationMode: "External engine",
    safety: "Live capable, gated",
    priority: "Later",
  },
  {
    repo: "AI4Finance-Foundation/FinRL",
    productName: "FinRL Research Sandbox",
    lane: "AI strategy research",
    bestUse: "Reinforcement-learning experiments and agent policy research.",
    featureUnlocked: "RL experiment tracker with overfit warnings, paper-only controls, and benchmark comparisons.",
    integrationMode: "Research sandbox",
    safety: "Research",
    priority: "Later",
  },
  {
    repo: "AI4Finance-Foundation/FinRL-Trading",
    productName: "FinRL-Trading Pipeline",
    lane: "AI-native quant infra",
    bestUse: "Modern AI quant pipeline experiments and paper-trading research infrastructure.",
    featureUnlocked: "AI-native pipeline map for data, feature engineering, model training, and paper validation.",
    integrationMode: "Research sandbox",
    safety: "Research",
    priority: "Later",
  },
  {
    repo: "AI4Finance-Foundation/FinGPT",
    productName: "FinGPT Sentiment Desk",
    lane: "Financial NLP",
    bestUse: "Financial news, filings, and social sentiment analysis.",
    featureUnlocked: "Headline sentiment, catalyst extraction, thesis contradiction checks, and source confidence.",
    integrationMode: "Research sandbox",
    safety: "Research",
    priority: "Next",
  },
  {
    repo: "jesse-ai/jesse",
    productName: "Jesse Crypto Lab",
    lane: "Crypto strategy",
    bestUse: "Crypto strategy research, exchange simulation, and crypto-specific paper workflows.",
    featureUnlocked: "Separate crypto strategy lane with exchange-aware assumptions and paper-first controls.",
    integrationMode: "External engine",
    safety: "Paper trading",
    priority: "Later",
  },
  {
    repo: "freqtrade/freqtrade",
    productName: "Freqtrade Crypto Strategy Lab",
    lane: "Crypto strategy automation",
    bestUse: "Self-hosted crypto dry-run/paper trading, backtesting, strategy optimization, exchange-aware reports, and strategy-risk review.",
    featureUnlocked: "Crypto-only strategy proof lane that can challenge setups with dry-run/backtest/hyperopt evidence while live exchange orders stay outside the app's worker bridge.",
    integrationMode: "External engine",
    safety: "Paper trading",
    priority: "Next",
  },
  {
    repo: "hummingbot/hummingbot",
    productName: "Hummingbot Liquidity Lab",
    lane: "Crypto market making",
    bestUse: "Self-hosted crypto market-making, liquidity, arbitrage-style, CEX/DEX/AMM connector readiness, dry-run/paper strategies, inventory and spread risk, and parameter review.",
    featureUnlocked: "Crypto liquidity proof lane that checks spreads, inventory skew, connector health, venue type, fees, and dry-run behavior without routing exchange orders through the app.",
    integrationMode: "External engine",
    safety: "Paper trading",
    priority: "Next",
  },
  {
    repo: "HKUDS/Vibe-Trading",
    productName: "Vibe Strategy Swarm",
    lane: "Cross-market strategy synthesis",
    bestUse: "Natural-language strategy generation, multi-agent team presets, cross-market backtests, validation, optimizers, and export workflows.",
    featureUnlocked: "Skill/swarm style strategy synthesis with validation discipline, cross-market awareness, and report-ready evidence summaries.",
    integrationMode: "Python worker",
    safety: "Research",
    priority: "Next",
  },
  {
    repo: "HKUDS/AI-Trader",
    productName: "AI-Trader Collective Signal Desk",
    lane: "Agent-native signal network",
    bestUse: "Collective AI trading signals, automated strategy workflows, and agent-native paper-trading research patterns.",
    featureUnlocked: "Consensus-style signal pressure, copy-trade caution, and crowd/agent disagreement checks before promotion.",
    integrationMode: "Research sandbox",
    safety: "Paper trading",
    priority: "Next",
  },
  {
    repo: "Polymarket/agents",
    productName: "Prediction Market Agent Desk",
    lane: "Event probability research",
    bestUse: "Prediction-market style agent utilities, RAG, news/web data sourcing, and event probability reasoning.",
    featureUnlocked: "Catalyst probability checks and event-market style disagreement signals without routing orders to Polymarket.",
    integrationMode: "Research sandbox",
    safety: "Research",
    priority: "Later",
  },
  {
    repo: "tensortrade-org/tensortrade",
    productName: "TensorTrade RL Lab",
    lane: "RL environment modeling",
    bestUse: "Composable reinforcement-learning environments, action schemes, reward functions, and data-feed experiments.",
    featureUnlocked: "Reward/action-policy scoring that treats every trade idea as an environment decision, not only a signal.",
    integrationMode: "Research sandbox",
    safety: "Research",
    priority: "Later",
  },
  {
    repo: "hsliuping/TradingAgents-CN",
    productName: "TradingAgents-CN Data Consensus",
    lane: "Localized multi-agent data QA",
    bestUse: "Multi-provider data fallback, Chinese-localized reporting, batch analysis, cache discipline, and data consistency checks.",
    featureUnlocked: "Data-consensus pressure that rewards redundant quote/fundamental agreement and punishes weak source coverage.",
    integrationMode: "Research sandbox",
    safety: "Research",
    priority: "Next",
  },
  {
    repo: "TraderAlice/OpenAlice",
    productName: "OpenAlice Guarded Lifecycle",
    lane: "Full trade lifecycle control",
    bestUse: "Trading-as-Git order staging, broker abstraction, guard pipelines, account snapshots, and human approval before execution.",
    featureUnlocked: "Lifecycle score from research to staged order, guard checks, paper mirroring, management cadence, and exit discipline.",
    integrationMode: "External engine",
    safety: "Live capable, gated",
    priority: "Next",
  },
  {
    repo: "brokermr810/QuantDinger",
    productName: "QuantDinger Unified Quant Ops",
    lane: "Research-to-operations stack",
    bestUse: "Unified research, strategy code, backtests, execution, alerts, operations, and AI-in-workflow product UX.",
    featureUnlocked: "Operational completeness scoring across strategy evidence, execution readiness, alerts, and workflow continuity.",
    integrationMode: "External engine",
    safety: "Paper trading",
    priority: "Next",
  },
  {
    repo: "The-Swarm-Corporation/AutoHedge",
    productName: "AutoHedge Risk Swarm",
    lane: "Swarm risk management",
    bestUse: "Director, quant, risk-management, and execution-agent stages for autonomous hedge-fund style research.",
    featureUnlocked: "Director-to-risk-to-execution staging that blocks weak ideas until risk and position sizing agree.",
    integrationMode: "Research sandbox",
    safety: "Paper trading",
    priority: "Next",
  },
];

export const engineWorkflow = [
  "Map every idea against the systematic-trading taxonomy: data, alpha thesis, analytics, backtest proof, live-trading controls, architecture, tools, and AI/LLM challenge lanes.",
  "Collect data with OpenBB/Alpha Vantage/OpenStock/Ghostfolio/AKShare-style connectors and current quote/news APIs.",
  "Challenge interesting tickers with TradingAgents and LLM-Trading-Lab-style agent logs before writing a trade thesis.",
  "Use Alphalens-style factor tear sheets to test whether ranks, quantiles, IC, and turnover support the signal.",
  "Use LSTM-Time-Series, StockPredictionAI, Stock-Prediction-Models, and LLM-Trading-Lab-style outputs as research pressure, not as trade authorization.",
  "Run simple first-pass validation in the native Backtest Lab.",
  "Stress-test parameters with a vectorbt-style sweep before trusting a setup.",
  "Promote only robust ideas to StockPredictionAI, LEAN, StockSharp, RQAlpha, Backtrader, Freqtrade, or Hummingbot for deeper forecast, event-driven, crypto strategy, and liquidity simulation.",
  "Use StockSight and FinGPT-style NLP to challenge the thesis with source-labeled sentiment, filings, and contradiction checks.",
  "Use StreetMerchant-style alert loops to show trigger state, channel readiness, cooldowns, and manual-action requirements before the operator reacts.",
  "Use Vibe-Trading and AutoHedge patterns to orchestrate specialist teams instead of trusting one model.",
  "Use OpenAlice and QuantDinger patterns to demand versioned orders, guard checks, alerts, and operations continuity.",
  "Use TensorTrade, AI-Trader, and Polymarket-agent patterns as RL, collective-signal, and event-probability pressure tests.",
  "Keep LLM Trading Lab, StockSight, StreetMerchant, LSTM Time Series, StockPredictionAI, Stock Prediction Models, Alpha Vantage, Alphalens, StockSharp, RQAlpha, FinRL, FinRL-Trading, TensorTrade, Nautilus, Freqtrade, Hummingbot, Jesse, OpenAlice, and all autonomous-agent lanes behind paper/live gates until broker keys, acknowledgement, audit storage, and risk controls exist.",
];
